services:
  wordpress:
    image: 'wordpress:latest'
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: '72.62.197.102:5896'
      WORDPRESS_DB_USER: abh
      WORDPRESS_DB_PASSWORD: 'abh#STRONGPASS'
      WORDPRESS_DB_NAME: pingFTPDB
      WORDPRESS_CONFIG_EXTRA: |
        @ini_set( 'upload_max_filesize', '512M' );
        @ini_set( 'post_max_size', '512M' );
        @ini_set( 'memory_limit', '1024M' );
        @ini_set( 'max_execution_time', '300' );
        @ini_set( 'max_input_time', '300' );
    volumes:
      - 'wordpress_data:/var/www/html'
volumes:
  wordpress_data: null
